version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - KlemenDEV
  assignees:
  - KlemenDEV
  labels:
  - dependencies
  ignore:
  - dependency-name: commons-io:commons-io
    versions:
    - "> 2.6"
  - dependency-name: org.reflections:reflections
    versions:
    - "> 0.9.9, < 0.10"
