# Configuration for Support Requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "invalid: support request"

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: >
  :wave: @{issue-author}, we use GitHub issue tracker exclusively for bug reports.
  However, this issue appears to be a support or a feature request. Please use our
  [Forums on the website](https://mcreator.net/forum) for support and feature requests.

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: true

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: true

# Repository to extend settings from
# _extends: repo
