commit_message: '[skip ci]'
files:
  - source: /plugins/mcreator-localization/lang/texts.properties
    translation: >-
      /plugins/mcreator-localization/lang/texts_%locale_with_underscore%.properties
