project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "/plugins/mcreator-localization/lang/texts.properties",
    "translation": "/plugins/mcreator-localization/lang/texts_%locale_with_underscore%.properties",
  },
  {
    "source": "/plugins/mcreator-link/lang/texts.properties",
    "translation": "/plugins/mcreator-link/lang/texts_%locale_with_underscore%.properties",
  }
]