# JetBrains Runtime (with JCEF) used to build and run MCreator, see platform/setup.gradle
jbr.version=25.0.3
jbr.build=b508.16

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=\
  ./jdk/jbr_win_64,\
  ./jdk/jbr_linux_64,\
  ./jdk/jbr_mac_x64/Contents/Home,\
  ./jdk/jbr_mac_aarch64/Contents/Home
