/*
 * MCreator (https://mcreator.net/)
 * Copyright (C) 2020 Pylo and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.mcreator.generator.mapping;

import net.mcreator.element.parts.IWorkspaceDependent;
import net.mcreator.generator.GeneratorWrapper;
import net.mcreator.minecraft.DataListEntry;
import net.mcreator.minecraft.DataListLoader;
import net.mcreator.util.TestUtil;
import net.mcreator.workspace.Workspace;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Map;
import java.util.Optional;

public abstract class MappableElement implements IWorkspaceDependent {

	private static final Logger LOG = LogManager.getLogger("Mappable Element");

	private final String value;

	protected transient final NameMapper mapper;

	private transient boolean managed;

	public MappableElement(NameMapper mapper) {
		this.mapper = mapper;
		this.value = null;
	}

	public MappableElement(NameMapper mapper, String value) {
		this.mapper = mapper;
		this.value = value;
	}

	@Override public String toString() {
		return getMappedValue();
	}

	public boolean isEmpty() {
		return value == null || value.isEmpty();
	}

	public String getMappedValue() {
		return getMappedValue(0);
	}

	public String getMappedValue(int mappingTable) {
		try {
			return mapper.getMapping(value, mappingTable);
		} catch (Exception e) {
			LOG.fatal("Failed to map value to the mappable element. Value: {}, mapper: {}", value,
					mapper.getMappingSource(), e);
			return value;
		}
	}

	public String getUnmappedValue() {
		return value;
	}

	/**
	 * @return true if the value exists in the workspace. Always returns true for vanilla elements,
	 * even if they are not supported in the selected Minecraft version. Returns false if the element is empty.
	 */
	public boolean isValidReference() {
		if (value == null || value.isEmpty())
			return false;

		Workspace workspace = getWorkspace();
		if (workspace == null) {
			return false;
		}
		return validateReference(value, workspace);
	}

	/**
	 * @return true if the value exists in the workspace. Always returns true for vanilla elements,
	 * even if they are not supported in the selected Minecraft version.
	 */
	public static boolean validateReference(@Nonnull String value, @Nonnull Workspace workspace) {
		if (value.startsWith(NameMapper.MCREATOR_PREFIX)) {
			boolean retval = workspace.containsModElement(GeneratorWrapper.getElementPlainName(value));
			if (!retval) {
				LOG.warn("Broken reference found. Referencing non-existent element: {}", value);
				TestUtil.failIfTestingEnvironment();
			}
			return retval;
		}
		return true;
	}

	public Optional<DataListEntry> getDataListEntry() {
		Map<String, DataListEntry> dataListEntryMap = DataListLoader.loadDataMap(mapper.getMappingSource());
		if (dataListEntryMap != null) {
			if (dataListEntryMap.containsKey(getUnmappedValue())) {
				return Optional.of(dataListEntryMap.get(getUnmappedValue()));
			}
		}

		return Optional.empty();
	}

	public String getDataListEntryType() {
		Optional<DataListEntry> dataListEntry = getDataListEntry();
		if (dataListEntry.isPresent()) {
			String type = dataListEntry.get().getType();
			return type != null ? type : "";
		}
		return "";
	}

	/**
	 * Call this to mark the current mappable element as managed - meaning it was not generated by a direct user input.
	 * Can be used to filter out elements that were not generated by the user in UI components, for example.
	 *
	 * @param managed true if the element is managed
	 */
	public void setManaged(boolean managed) {
		this.managed = managed;
	}

	/**
	 * @return true if the element was marked as managed
	 * @see #setManaged(boolean)
	 */
	public boolean isManaged() {
		return managed;
	}

	@Override public void setWorkspace(@Nullable Workspace workspace) {
		mapper.setWorkspace(workspace);
	}

	@Nullable @Override public Workspace getWorkspace() {
		return mapper.getWorkspace();
	}

	@Override public int hashCode() {
		return value == null ? 0 : value.hashCode();
	}

	@Override public boolean equals(Object element) {
		return element instanceof MappableElement && (value != null && value.equals(((MappableElement) element).value));
	}

}
