/*
 * MCreator (https://mcreator.net/)
 * Copyright (C) 2012-2020, Pylo
 * Copyright (C) 2020-2026, Pylo, opensource contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.mcreator.ui.mcp.tools;

import net.mcreator.generator.GeneratorTemplate;
import net.mcreator.generator.io.GradleTrackingFileIO;
import net.mcreator.io.FileIO;
import net.mcreator.io.mcp.protocol.SchemaDescription;
import net.mcreator.io.mcp.tool.ToolResult;
import net.mcreator.ui.MCreator;
import net.mcreator.ui.MCreatorTabs;
import net.mcreator.ui.component.util.ThreadUtil;
import net.mcreator.ui.ide.CodeEditorView;
import net.mcreator.ui.mcp.MCreatorMcpTool;
import net.mcreator.ui.mcp.tools.utils.ProjectFileUtils;
import net.mcreator.workspace.elements.ModElement;

import javax.annotation.Nullable;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class ProjectFileEditTool extends MCreatorMcpTool<ProjectFileEditTool.Args> {

	public static class Args {
		public Action actionType;
		@SchemaDescription("Workspace-relative file path as returned by project_files SEARCH action")
		public String path;
		@SchemaDescription("Full new file content for WRITE") @Nullable public String content;
		@SchemaDescription("Exact text to replace for EDIT, must occur exactly once in the file") @Nullable
		public String oldText;
		@SchemaDescription("Replacement text for EDIT, may be empty to remove oldText") @Nullable public String newText;

		public enum Action {
			WRITE, EDIT, DELETE
		}
	}

	public ProjectFileEditTool(Supplier<MCreator> currentMCreator) {
		super(currentMCreator, Args.class);
	}

	@Override public String getName() {
		return "project_file_edit";
	}

	@Override public String getDescription() {
		return """
				Creates, edits, or deletes project files inside the source root of the workspace.\
				 WRITE writes the full content to the file, creating it and missing parent folders if needed.\
				 EDIT replaces a single exact occurrence of oldText in an existing file with newText.\
				 DELETE removes an existing file.\
				 Files belonging to a mod element can only be edited or deleted if the element code is locked \
				 (see mod_element_definition tool LOCK_CODE action), otherwise the changes would be overwritten by the generator.\
				 Workspace base files generated by MCreator can not be deleted and only their user code blocks persist edits.\
				 Use project_files tool to search and read files.""";
	}

	@Override protected Boolean getReadOnlyHint() {
		return false;
	}

	@Override protected Boolean getDestructiveHint() {
		return true;
	}

	@Override protected CompletableFuture<ToolResult> call(MCreator mcreator, Args input) throws IOException {
		if (input.actionType == null) {
			return completedError("actionType is required");
		}
		if (input.path == null || input.path.isBlank()) {
			return completedError("path is required");
		}

		Path workspaceRoot = ProjectFileUtils.getWorkspaceRoot(mcreator);
		Path root = ProjectFileUtils.getCommonRoot(mcreator);
		if (root == null) {
			return completedError("Workspace has no source root");
		}

		File file = ProjectFileUtils.resolveFile(workspaceRoot, root, input.path);
		if (file == null) {
			return completedError("Path is outside of the source root: " + input.path);
		}
		if (file.isDirectory()) {
			return completedError("Path is a directory: " + input.path);
		}
		String relativePath = ProjectFileUtils.getPathInWorkspace(workspaceRoot, file);

		return switch (input.actionType) {
			case WRITE -> write(mcreator, file, relativePath, input.content);
			case EDIT -> edit(mcreator, file, relativePath, input.oldText, input.newText);
			case DELETE -> delete(mcreator, file, relativePath);
		};
	}

	private static CompletableFuture<ToolResult> write(MCreator mcreator, File file, String relativePath,
			@Nullable String content) {
		if (content == null) {
			return completedError("content is required for WRITE");
		}

		boolean existed = file.isFile();
		FileOwnership ownership = FileOwnership.of(mcreator, file);
		String unlockedError = ownership.getUnlockedModElementError();
		if (unlockedError != null) {
			return completedError(unlockedError);
		}

		GradleTrackingFileIO.writeFile(mcreator.getWorkspace(), content, file);

		Map<String, Object> response = new LinkedHashMap<>();
		response.put("result", (existed ? "File written: " : "File created: ") + relativePath);
		return completed(finishWrite(mcreator, file, ownership, response));
	}

	private static CompletableFuture<ToolResult> edit(MCreator mcreator, File file, String relativePath,
			@Nullable String oldText, @Nullable String newText) {
		if (oldText == null || oldText.isEmpty()) {
			return completedError("oldText is required for EDIT");
		}
		if (newText == null) {
			return completedError("newText is required for EDIT");
		}
		if (!file.isFile()) {
			return completedError("File not found: " + relativePath);
		}

		FileOwnership ownership = FileOwnership.of(mcreator, file);
		String unlockedError = ownership.getUnlockedModElementError();
		if (unlockedError != null) {
			return completedError(unlockedError);
		}

		String original = FileIO.readFileToString(file);
		boolean crlf = original.contains("\r\n");
		String current = original.replace("\r\n", "\n");
		oldText = oldText.replace("\r\n", "\n");
		newText = newText.replace("\r\n", "\n");

		int first = current.indexOf(oldText);
		if (first < 0) {
			return completedError("oldText not found in file: " + relativePath);
		}
		if (current.indexOf(oldText, first + oldText.length()) >= 0) {
			return completedError(
					"oldText occurs more than once in file, provide more context to make it unique: " + relativePath);
		}

		String updated = current.substring(0, first) + newText + current.substring(first + oldText.length());
		if (crlf) {
			updated = updated.replace("\n", "\r\n");
		}
		GradleTrackingFileIO.writeFile(mcreator.getWorkspace(), updated, file);

		Map<String, Object> response = new LinkedHashMap<>();
		response.put("result", "File edited: " + relativePath);
		return completed(finishWrite(mcreator, file, ownership, response));
	}

	private static CompletableFuture<ToolResult> delete(MCreator mcreator, File file, String relativePath) {
		if (!file.isFile()) {
			return completedError("File not found: " + relativePath);
		}

		FileOwnership ownership = FileOwnership.of(mcreator, file);
		String unlockedError = ownership.getUnlockedModElementError();
		if (unlockedError != null) {
			return completedError(unlockedError);
		}
		if (ownership.baseFile()) {
			return completedError(
					"File is a workspace base file generated by MCreator and can not be deleted: " + relativePath);
		}

		GradleTrackingFileIO.deleteFile(mcreator.getWorkspace(), file);
		if (file.exists()) {
			return completedError("Failed to delete file: " + relativePath);
		}

		ThreadUtil.runOnSwingThreadAndWait(() -> {
			for (MCreatorTabs.Tab tab : new ArrayList<>(mcreator.getTabs().getTabs())) {
				if (tab.getContent() instanceof CodeEditorView editor && isSameFile(editor.fileWorkingOn, file)) {
					mcreator.getTabs().closeTab(tab, true);
				}
			}
			mcreator.getProjectBrowser().reloadTree();
		});
		refreshSourceInfoIfJava(mcreator, file);

		Map<String, Object> response = new LinkedHashMap<>();
		response.put("result", "File deleted: " + relativePath);
		if (ownership.modElement() != null) {
			response.put("note", "Deleted file belonged to code locked mod element " + ownership.modElement().getName()
					+ ". The element definition still references this file.");
		}
		return completedObject(response);
	}

	private static ToolResult finishWrite(MCreator mcreator, File file, FileOwnership ownership,
			Map<String, Object> response) {
		List<String> notes = new ArrayList<>();
		if (ownership.baseFile()) {
			notes.add("""
					This file is a workspace base file generated by MCreator. Only code inside user code blocks (lines between \
					"Start of user code block <name>" and "End of user code block <name>" comments) persists; all other \
					changes are discarded when the workspace code is regenerated.""");
		}
		if (ownership.modElement() != null) {
			notes.add("File belongs to code locked mod element " + ownership.modElement().getName()
					+ ". Unlocking the element code will regenerate this file and discard the changes.");
		}

		List<String> warnings = new ArrayList<>();
		ThreadUtil.runOnSwingThreadAndWait(() -> {
			for (MCreatorTabs.Tab tab : mcreator.getTabs().getTabs()) {
				if (tab.getContent() instanceof CodeEditorView editor && isSameFile(editor.fileWorkingOn, file)) {
					if (editor.wasChanged()) {
						warnings.add("File is open in the code editor with unsaved changes. The editor was not "
								+ "reloaded and saving it would overwrite this change.");
					} else if (!editor.readOnly) {
						editor.reloadCode();
					}
				}
			}
			mcreator.getProjectBrowser().reloadTree();
		});
		refreshSourceInfoIfJava(mcreator, file);

		if (!notes.isEmpty()) {
			response.put("notes", notes);
		}
		if (!warnings.isEmpty()) {
			response.put("warnings", warnings);
		}
		return ToolResult.object(response);
	}

	private static void refreshSourceInfoIfJava(MCreator mcreator, File file) {
		if (file.getName().endsWith(".java")) {
			mcreator.getGenerator().refreshWorkspaceSourceInfo();
		}
	}

	private static boolean isSameFile(@Nullable File a, File b) {
		if (a == null) {
			return false;
		}
		try {
			return a.getCanonicalFile().equals(b.getCanonicalFile());
		} catch (IOException e) {
			return false;
		}
	}

	/**
	 * @param modElement Mod element the file belongs to, or null if the file is not a mod element file
	 * @param baseFile   True if the file is a workspace base file generated by MCreator
	 */
	private record FileOwnership(@Nullable ModElement modElement, boolean baseFile) {

		static FileOwnership of(MCreator mcreator, File file) {
			if (!file.isFile()) {
				return new FileOwnership(null, false);
			}
			ModElement modElement = mcreator.getGenerator().getModElementThisFileBelongsTo(file);
			List<File> baseFiles = mcreator.getGenerator().getModBaseGeneratorTemplatesList().stream()
					.map(GeneratorTemplate::getFile).toList();
			return new FileOwnership(modElement, FileIO.isFileOnFileList(baseFiles, file));
		}

		/**
		 * @return error message if the file belongs to a mod element whose code is not locked, null otherwise
		 */
		@Nullable String getUnlockedModElementError() {
			if (modElement == null || modElement.isCodeLocked()) {
				return null;
			}
			return "File belongs to mod element " + modElement.getName()
					+ " whose code is not locked, so it is generated from the element JSON definition and any changes "
					+ "would be overwritten. Use mod_element_definition tool to change the element definition instead, "
					+ "or lock the element code first with LOCK_CODE action if there is no other option.";
		}

	}

}
