name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.2.0
      with:
        upload_translations: true
        
        download_translations: true
        commit_message: '[skip ci] New Crowdin translations by Github Action'
        
        create_pull_request: false
        
        source: /plugins/mcreator-localization/lang/texts.properties
        translation: >-
          /plugins/mcreator-localization/lang/texts_%locale_with_underscore%.properties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
