name: Crowdin push new translation keys

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: crowdin action
      uses: crowdin/github-action@1.2.0
      with:
        upload_translations: true
        project_id_env: CROWDIN_PROJECT_ID
        api_token_env: CROWDIN_PERSONAL_TOKEN
        source: /plugins/mcreator-localization/lang/texts.properties
        translation: >-
          /plugins/mcreator-localization/lang/texts_%locale_with_underscore%.properties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
